export const DS_ROUTE_ACTIVATED = 'DS_ROUTE_ACTIVATED';
export const DS_ROUTE_DEACTIVATED = 'DS_ROUTE_DEACTIVATED';
export const DS_ROUTE_PARAMS_LOADED = 'DS_ROUTE_PARAMS_LOADED';

export const DS_FIND_RECORD_REQUESTED = 'DS_FIND_RECORD_REQUESTED';
export const DS_FIND_RECORD_SUCCEEDED = 'DS_FIND_RECORD_SUCCEEDED';
export const DS_FIND_RECORD_FAILED = 'DS_FIND_RECORD_FAILED';
